### PR TITLE
Allow enabling helm templating in kustomize base

### PR DESCRIPTION
**Pull request by bradonkanyid**
This has the same effect as `--enable-helm` in the kustomize cli, as
well as allowing setting a different path for the helm binary.

I assume there's more discussion necessary, but this is actually enough to get plans and applies working as-is. I wanted to verify this would be something that could be accepted before writing further tests and such.

### CODE REVIEW

**Comment by pst** [comment]
I have no objections to include this. I've never used it myself though and therefor have no guidance I can give.

One question would be, do we also need it for the `kustomization_overlay` data source too?

Assuming people may want to target helm charts there too? And, where in the `kustomization.yaml` would the helm chart be referenced, is it bases? Or do we need to add a helm specific attribute to the overlay data source for this?

**Comment by rattboi** [comment]
https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md 

Here's the documentation on the feature. I don't *believe* it makes sense to use a `helmChart` kustomization in an overlay, but perhaps I'm wrong on that. I have not yet found any examples of using `helmChart` in an overlay.

I don't believe overlays would be affected.

**Comment by bradonkanyid** [comment]
What are other requirements towards making this PR mergeable?

I could add a few tests, and I believe we'd need to install helm in the CI flow.

**Comment by pst** [comment]
`kustomization_overlay` supports defining a kustomization in YAML. It should support anything that you can put into a `kustomization.yaml`. So if that's the case for charts, we should add it there too.

Yes, tests should be included in the PR. Both for the data sources, as well as for the kustomization_resource.

**Comment by rattboi** [comment]
If it's necessary for overlays as well, would it make sense to move these options to the provider config instead so you don't need to continually specify "yes, I want to use helm" in every `kustomization_xxx` data source?

**Comment by pst** [comment]
I'd say let's not complicate this PR by adding in a breaking change for users.

**Comment by rattboi** [comment]
How does this initial test look? I was expecting the Github Actions runner to run the test suite against this, and we'd see that helm was missing, but I don't see it doing that.

**Comment by bradonkanyid** [comment]
https://github.com/BlueOwlDev/terraform-provider-kustomization/runs/4248132665?check_suite_focus=true

I was able to run the tests from my fork, and it looks like helm is available for the test runner, and everything is passing. Just gotta fill out more tests.

**Comment by rattboi** [comment]
@pst ok, I was definitely mistaken about the `kustomization_overlay` data source not needing support. However, I'm struggling to understand what sort any test of `kustomization_resource` would demonstrate. If the schema is all validated and fits the `ids`/`ids_prio`/`manifests` expected format, then helm (and kustomize, really) are out of the picture, no?

What sorts of other tests would you like to see?

**Review by pst — APPROVED** [review]
Thanks for the contribution. I think a happy path test is good enough. We don't need to verify `kustomize` or `helm` working correctly. Just that if the attributes are set in Terraform the expected response is returned.

**Comment by rattboi** [comment]
Any chance of a new release cut soon?

**Comment by pst** [comment]
Done https://github.com/kbst/terraform-provider-kustomization/releases/tag/v0.7.1

**Pull request merged**
