### PR TITLE
Redo #30 and fix test

### PR DESCRIPTION
**Pull request by maxiaohao**
Seems there is a permission issue for me to create a direct branch in repo `kbst/terraform-provider-kustomize` (described [here](https://github.com/kbst/terraform-provider-kustomize/pull/30#issuecomment-660657839)).
This PR is the fix for tests based on #30: 
1. Though the new terraform plan diff is based on the fields in targeted kustomize data, fiels inside an array is still not able to be processed in the json merge, as a result and compromise, we have to satisfy the targeted array elements by having all fields returned from the cluster, such as `imagePullPolicy: Always` under the `containers` array. 
2. `creationTimestamp: null` in targeted kustomize data will always differ from the value returned from cluster with a concrete timestamp value. Removing `creationTimestamp: null` fixes it. 
3. Note I've turned off all the `ImportStateVerify` tests, that is actually due to a limitation of `terraform import` that is not aware of the `data`: https://www.terraform.io/docs/commands/import.html#provider-configuration. The fact is that when doing an `import`, the targeted kustomization from `data` is not configured at all, causing it to be empty thus the state imported is the "full" manifest without a "base" to compare and process at all. This sounds another flaw of this targeted data approach. People usually have to do an extra terraform apply after the import to have the states trimmed and sync'd. Note this is not a problem specific to our provider but is a terraform wide limitation, other providers using `data` suffer it too, like this: https://github.com/hashicorp/terraform/issues/17847

### CODE REVIEW

**Comment by pst** [comment]
All the tests worked before and the test manifests are valid. Having `creationTimestamp: null` set and `imagePullPolicy: Always` not set is a use-case the provider needs to support.

If we merge the proposed change, we would force users to make changes to their valid K8s manifests that have previously worked and would work fine with `kubectl`. I am not convinced this is the right way forward. I think keeping a more verbose diff is the better option.

**Comment by maxiaohao** [comment]
People with `creationTimestamp: null` or without `imagePullPolicy: Always` (in the array) will not be forced to change them, instead they just keep getting diff in terraform plan.
I made such changes to the test manifest just to satisfy the terraform test framework's expectation of a "zero diff after apply" (there is a test after a terraform apply asserting no diff should be found in a following terraform plan).
They fall into two tiers:
1. Fields like `creationTimestamp` and `resourceVersion` that are calculated and assigned on server side are preferred to be omitted in kustomize. Keeping them would incur noisy diffs on terraform plan. If people really want to keep these fields in kustomize and intend not to see the plan diff, they need to change those values to what are actually on server (k8s cluster), e.g., grab the actual `creationTimestamp` value of a resource once it's applied and use that value in kustomize to mute further plan diffs. On the other hand, the value `null` of `creationTimestamp` is an edge case that the propsed new json strip-and-diff approach would skip comparing that will always result in an addition of `+ creationTimestamp = null`, because such null fields are stripped in the 2x 3-way diff for producing the plan diff from actual k8s resource. 
2. Similarly but not exactly same as 1), fields in an array, for example, the `imagePullPolicy: Always` as one of the fields in `container[0]` in a deployment, can pop up as a deletion in the plan diff (not defined in kustomize manifest, but does exist on server). Reason is that I don't do a "strip" on an array element at all, meaning, we don't pre-process the `container[0]` from server against the "targeted" `container[0]` to hide any fields inside it. People are suggested to amend their kustomize code by adding the `imagePullPolicy: Always` propagated by server, once they see the planned diff after their first apply. Otherwise they will keep seeing that plan diff of such "deletions". There can be a resolve of this issue by doing deeper "strip" of the fields in arrays too, on an element-by-element basis (`container[0] vs container[0]`, `container[1] vs container[1]`, ...), like how we've been stripping the basic fields of a resource against the "targeted" object.

> I think keeping a more verbose diff is the better option.
This would absolutely keep the logic as simple and straightforward for us, however I reckon keeping all the verbose plan may frustrate people by repeating too much diff, especially for thhose having hundreds of resources to maintain.

All in all, I feel both issue 1 and 2 as I described above are just minor noises if people don't choose to change their existing kustomize code. Compared to the full verbose diff, those minor diffs could be more acceptable in my opinion. And issue 2 could even be resolved with some further work doing the "targeted" strip too on array element level. 

If you have more reasons going for the simple "verbose diff" way, please let me know and we can have more discussion and evaluation around it.

**Comment by maxiaohao** [comment]
@pst In addition I've turned the import to only save "minimal" identity of the resource instead of a full manifest so as to have all the tests fixed. 
Also a "Limitations" section has been added to `README.md` to make some clarification.

**Comment by pst** [comment]
Ok, I've done some more testing.

## Current implementation

```
$ terraform version
Terraform v0.12.24
+ provider.kustomization v0-beforechange
```

I run a `terraform apply` for a Istio installation, to have something sizeable. This results in:

```
Apply complete! Resources: 63 added, 0 changed, 0 destroyed.
```

Now, running a `terrafrom plan` returns, as expected:

```
No changes. Infrastructure is up-to-date.
```

When I now switch to the new implementation:

## New implementation

```
$ terraform version
Terraform v0.12.24
+ provider.kustomization v1-afterchange
```

I run `terraform init` and then `terraform plan` I get:

```
Plan: 0 to add, 8 to change, 0 to destroy.
```

You can see the [full diff](https://gist.github.com/pst/02c284bc4e65b707d4db9aa0dbe6d779) in a Gist, it's quite long.

I assumed, this was only because of switching from the old version to the new. So I run `terraform apply`

```
Apply complete! Resources: 0 added, 8 changed, 0 destroyed.
```

The **problem** is however, running a `terraform plan` now, will again plan to make the same changes:

```
Plan: 0 to add, 8 to change, 0 to destroy.
```

@maxiaohao I still agree with you, less verbose diffs would be good. But this proposed implementation has too many side effects. I did some reading and it seems the [`CustomizeDiff`](https://github.com/hashicorp/terraform-plugin-sdk/blob/9da7cbac0dfcd4c7096105eeda94ea69f53c1101/helper/schema/resource.go#L146) function could potentially be used to change the displayed diff, without touching the actual state. Maybe that's a viable approach?

**Comment by maxiaohao** [comment]
Hi @pst, 

The diffs in the gist look to be due to the array elements in the json which are not stripped in the current `simplifyJSON` using `jsonmergepatch`. 
In the above issue 2) as I mentioned, I think a new implementation with array element-by-element simplification could eliminate such annoying diffs. 
The bigger concern is 1) with such as `creationTimestamp: null` legally in user's kustomization, we'll not be able to suppress the diff against the "computed" values from actual resource, however I think leaving such diff to users is not a bad idea. 
Please let me know if you are Okay with that plan? If so I'd like to spend more time doing a new implementation of the `simplifyJSON` with raw json data traversal so resolve issue 2).

On `CustomizeDiff`, that's a good point. I had a look at it and basically I feel we can make use of `diff.SetNew` to align `new` (users' kustomization, tf config) with `old` (state). 
Note that asks for a change from 
a) storing the simpilfied slim json (no field above kustomization/tf config will be stored), to 
b) storing the full manifest from k8s cluster directly into state.
We are currently with a) in this PR and we have limitations (as mentioned in the readme) in terraform import and refresh where kustomization/users' tf config is not involved where this "target-based" approach requires it. 
So I think b) could be a better way to go. Though it requires to change the `schema` to `optional` and `computed`, plus when showing the diff, the whole state'll look bit long and off what is defined in kustomization/tf config, as long as we do the the custom diff properly with the new impl of `simplifyJSON`, I bet we could be rather precise in showing the diff. 
Please also evaluate the idea of b) and let me know what you think. 
Thanks!

**Comment by pst** [comment]
I would:

 1. Take a fresh start and go back to the previous implementation with the `last-applied-config` annotation to get rid of all the import issues
 1. Investigate if either [`CustomizeDiffFunc`](https://pkg.go.dev/github.com/hashicorp/terraform/helper/schema?tab=doc#CustomizeDiffFunc) or [`SchemaDiffSuppressFunc`](https://pkg.go.dev/github.com/hashicorp/terraform/helper/schema?tab=doc#SchemaDiffSuppressFunc) can be used to cleanup the diff
 1. Try to let the K8s API's server-side-dry-run handle as much of the cleanup as possible. It has access to the OpenAPI schema and should therefor do a better job than a client side 3-way merge

This provider should stay as simple as possible. Leave the hard things to the Kubernetes API. If that's not possible, stick with the more verbose diff.

**Comment by pst** [comment]
This has been stale for quite a while. I'll go ahead and close it.

**Comment by maxiaohao** [comment]
Yeah I did more attempts earlier regarding the `CustomizeDiffFunc` or `SchemaDiffSuppressFunc` etc. and seemed none could give a neat fix in terms of the diff stuff. Probably need a look into some other directions in the future.

**Pull request closed without merging**
