### PR TITLE
Allow kustomization plugin to run in-cluster

### PR DESCRIPTION
**Pull request by willthames**
Ensure that plugin can run in cluster

### CODE REVIEW

**Comment by pst** [comment]
You can already run it inside a cluster by giving it a kubeconfig that instructs it to do so:

```
locals {
  kubeconfig = yamlencode({
    apiVersion      = "v1"
    kind            = "Config"
    preferences     = {}
    current-context = "incluster"
    clusters = [
      {
        name = "incluster"
        cluster = {
          certificate-authority-data = filebase64(var.kubeconfig_ca_path)
          server                     = var.kubeconfig_server
        }
      }
    ]
    users = [
      {
        name = "incluster"
        user = {
          token = file(var.kubeconfig_token_path)
        }
      }
    ]
    contexts = [
      {
        name = "incluster"
        context = {
          cluster = "incluster"
          user    = "incluster"
        }
      }
    ]
  })
}

provider "kustomization" {
  kubeconfig_raw = local.kubeconfig
}
```

That being said, your implementation in the provider makes it significantly more convenient. However, there's been a lot of concerns in the [past](https://github.com/kbst/terraform-provider-kustomization/issues/90), about the provider implicitly configuring itself. That's why I moved to the hard requirement that one of `kubeconfig_path` or `kubeconfig_raw` has to be set explicitly. So I suggest to add a third option, e.g. `kubeconfig_incluster` to keep this explicit. The incluster option, like the path should probably also be available via a environment variable.

**Comment by willthames** [comment]
I can live with `kubeconfig_incluster`

**Comment by willthames** [comment]
@pst hopefully my changes to this implementation meet the desired goals

**Comment by pst** [comment]
Thanks, glad you accepted the explicit config. I did not want to force another change regarding this on users.

**Pull request merged**
