### PR TITLE
Upgrade to Terraform Provider SDK v2

### PR DESCRIPTION
**Pull request by pst**

### CODE REVIEW

**Comment by willthames** [comment]
@pst what are the future plans for this - the reshaping of the configuration seems like another thing that might be worth adding as a breaking change sooner rather than later

This might be good to do before adding support for replacements (assuming that's a goal)

Also do you have any thoughts on whether v2 makes sense as a target these days or just bite the bullet and move to framework (although framework relies on terraform 1.0.3+ which may well be a leap too far!)

**Comment by pst** [comment]
```
panic: proto: file "extensions/extension.proto" is already registered
        previously from: "github.com/googleapis/gnostic/extensions"
        currently from:  "github.com/google/gnostic/extensions"
```

**Comment by willthames** [comment]
@pst - any chance that we could have a `0.8.0-rc1` tag (or similar) so that we can try this out before it goes live?

**Comment by pst** [comment]
The release was still in draft. So I assume you could not see it. https://github.com/kbst/terraform-provider-kustomization/releases/tag/v0.8.0-rc0

I don't think the `-rcX` tags are available from the terraform registry though.

**Comment by pst** [comment]
I still need to update the docs for the schema changes. But you can see required changes here: https://github.com/kbst/catalog/commit/f136940a812ce0e6e7efd41c9223f595472e7252

Basically `target`, `obj_ref` and `field_ref` are blocks now, because the old schema was not valid anymore with SDK v2.

**Comment by willthames** [comment]
> I don't think the `-rcX` tags are available from the terraform registry though.

You can choose  0.8.0-rc0 in the version drop down but it will never default to the prerelease
https://registry.terraform.io/providers/kbst/kustomization/0.8.0-rc0

I see 0.8.0 is live now, look forward to trying it out!

**Comment by pst** [comment]
I added a feature to opt out of the compression feature entirely. Just in case. But once disabled big CRDs will continue to fail. I found one bug in `v0.8.0`. https://github.com/kbst/terraform-provider-kustomization/issues/169 I forgot to have a schema migration for the data source. So for existing configurations, you may want to wait for `v0.8.1`.

**Pull request merged**
