### PR TITLE
Update kustomize dependencies

### PR DESCRIPTION
**Pull request by willthames**
Migrate to latest kustomize/api (v0.10.0) and latest
kustomize/kyaml (v0.12.0)

### CODE REVIEW

**Comment by willthames** [comment]
This addresses #126 but there's one failing test remaining - as I suspect I'm on a diametrically opposing timezone I'll leave this here for my overnight and look at it again in the morning

**Comment by pst** [comment]
The main reason that blocked updating the Kustomize version in the provider was the issue with kyaml not supporting anchors. But this should be resolved according to upstream https://github.com/kubernetes-sigs/kustomize/issues/3675

Happy to merge this as soon as tests pass.

**Comment by willthames** [comment]
The remaining test appears to just be a change in the result of the hash that kustomize generates for a secret. 

All tests now pass

**Comment by pst** [comment]
Yeah the hash is based on the content of the secret or configMap and if that changes, e.g. a line ending is removed the entire hash changes. I'll test this, merge it and fix the hash.

Thanks for your work on this.

**Comment by willthames** [comment]
@pst - the hash is fixed in this PR now - all tests pass locally for me

**Comment by pst** [comment]
I can confirm, tests pass just fine. Thanks again.

**Pull request merged**
